# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_first_name: <%= ENV["ADMIN_FIRST"] %>
  admin_last_name: <%= ENV["ADMIN_LAST"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_password: <%= ENV["MANDRILL_PASSWORD"] %>
  domain_name: aquarimeter.rocks
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  domain_name: aquarimeter.rocks
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
   admin_first_name: <%= ENV["ADMIN_FIRST_NAME"] %>
    admin_last_name: <%= ENV["ADMIN_LAST_NAME"] %>
    admin_email: <%= ENV["ADMIN_EMAIL"] %>
    admin_password: <%= ENV["ADMIN_PASSWORD"] %>
    email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
    email_provider_password: <%= ENV["MANDRILL_PASSWORD"] %>
    domain_name: aquarimeter.rocks
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
